name: Prettier Formatting

on:
  push: {}

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Adjust to your Node.js version

      - name: Install dependencies
        run: npm install  # Adjust if you're using a different package manager

      - name: Apply Prettier Formatting
        run: npm run format
